### ISSUE TITLE
demo.sh produces empty files with gensim

### ISSUE THREAD

**Issue by piskvorky** [uwdata/termite-data-server#7]
Great project! Love the idea, something like this is sorely missing, thanks. Allison's TMVE project died somehow.

I'm trying different things with Termite now, so I may be opening a few issues. First one is that demo.sh produces empty files with gensim:

```
$ python
Python 2.7.1 (r271:86832, Aug  5 2011, 03:30:24)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
$ time ./demo.sh 20newsgroups gensim
real    12m10.081s
user    12m3.673s
sys 0m5.281s
$ ls -l ./apps/20newsgroups_gensim/data/lda
total 40
-rw-r--r--  1 kofola  staff    2 Feb 20 18:13 doc-index.json
-rw-r--r--  1 kofola  staff    2 Feb 20 18:13 doc-topic-matrix.txt
-rw-r--r--  1 kofola  staff    2 Feb 20 18:13 term-index.json
-rw-r--r--  1 kofola  staff    2 Feb 20 18:13 term-topic-matrix.txt
-rw-r--r--  1 kofola  staff  511 Feb 20 18:13 topic-index.json
```

**Comment by jcchuang** [comment]
Hi @piskvorky : Would it be possible to get a copy of your full terminal transcript, so I can get a sense of what might have gone wrong when you run the demo script?  I'm happy to jump on a skype call if needed.

On the other hand, I can't find a way to dump the topical mixture per document from gensim.  What's the best way to access that information, so I can generate doc-topic-matrix.txt?

**Comment by piskvorky** [comment]
In gensim, you get a document's topics with `topics = model[document]`.

Skype is fine :)

**Comment by jcchuang** [comment]
Hi @piskvorky 

How do I get a list of document IDs, in order to feed them into either model[document]?

Alternatively, would it be more efficient to call model.interference() instead to get the topical mixtures associated with all documents?  If so, what should I pass in as the first argument 'chunk'?

**Comment by piskvorky** [comment]
The `document` = sparse vector, for example `[(1, 2.5), (12, 8), ..., (feature_id, feature_weight)]`

Calling `model[sparse_vector]` (or `model[corpus_aka_iterable_of_sparse_vectors]`) transforms the input into topics.

In case of LDA, `lda_model[sparse_vector]` returns the topics and their weights (here, probabilities), for example `[(0, 0.9), (1, 0.03), ..., (topic_id, topic_weight)]`.

Model transformations can be piped, for example `topics = lsi_model[tfidf_model[sparse_vector]]`.

A [quick example](http://radimrehurek.com/gensim/tutorial.html#quick-example) from the tutorials.

**Comment by jcchuang** [comment]
Got it.  I'm now saving the TextCorpus instead of Dictionary object, so that I can retrieve the list of documents.  I just pushed out a fairly large chunk of code change, that uses SQLite3 DB as the underlying storage, and rewrote all of the training/importing scripts.  Let me know if you encounter any further issues!
